# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Ubuntu Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
        #- run: npm test
      - name: SSH Remote Commands
        # You may pin to the exact commit or the version.
        # uses: appleboy/ssh-action@55dabf81b49d4120609345970c91507e2d734799
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.VM_IP}}
          port: 3031
          username: ${{secrets.VM_USERNAME}}
          key: ${{secrets.VM_SSH}}
          script: |
            cd ~/w/projects/tag-your-links-frontend
            echo "Changed directory"
            git pull
            echo "Git pull completed"
            npm install
            echo "npm install completed"
            npm run build
            echo "npm run build"
            cp -r dist/* /var/www/test-url.ir
            echo "Files copied"
